# we are going to use just the NATIVE filesystem (not a Git backend or a database)
server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:config/